client/package-lock.json
client/package.json
package-lock.json

npm install in the client folder was throwing an error that it needed the typescript package.  This commit installs it and solves the error.

install typescript package

---

models/Challenge.js
models/User.js
routes/API.js

Changed the challenge model:
-Added startDate. createdAt and an array of string for the description of each day
Prepared the querys to:
-Create a challenge
-Get number of users in a challenge
-Get challenges belonging to a user
-Add user to a challenge
-Remove user from a challenge

Change Challenge model and query

---

client/package-lock.json
client/package.json
client/src/utils/API.js
routes/API.js

Added APIs on React

---

bin/authService.js

-When logging, if the user already exist... it wont be created again, just redirect
-Tried to save something related to the user logging using localstorage, but apparently can't be done from server side (At least what i read). Currently saving the username in a cookie so we can know which user is active. 
-The cookie should be read at the beginning of the initial page to know it the user is already logged in and on profile to display the information, this information should be saved on a state probably?

Avoid duplicate users & create users

---

bin/authService.js
client/src/App.js

-The function was created on the app.js, probably needs to be moved somewhere else where is actually needed

Save username cookie when logging in, created a function to read the cookie on react

---

client/src/Components/Pages/CreateChallenges/index.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/ProfileNav/index.js

- CreateChallenge inputs are all linked to state. Ready to make API call. 
- Need to add validation and required fields still

Fix create challenge form

---

client/src/Components/Pages/BrowseChallenges/index.js
client/src/Components/Pages/ChallengeCard/index.js
client/src/Components/Pages/ChallengeDetails/ChallengeDetails.css
client/src/Components/Pages/ChallengeDetails/index.js
client/src/Components/Pages/Profile/index.js
client/src/Components/UiComponents/Form/index.js

- Added component for challenge details
- Component renders when clicking on a challenge title in browse challenges component
- ID is in the route params (props)
- Ready to dynamically update when component mounts with API function

Challenge component

---

client/src/Components/Pages/CreateChallenges/index.js

-Missing what to do after,
-Only adds the challenge to the DB

Create challenge function created

---

client/src/App.js
client/src/utils/API.js
routes/API.js

-If there is a cookie, the user state will be updated to the object of the user found on the api call
-We will need to pass this state to profile?

Created user state on App.js

---

bin/authService.js

Simplified version of auth

---

bin/authService.js
client/src/App.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/ProfileNav/index.js
client/src/utils/API.js
routes/API.js

-Cookie changed from username to id from instagram

Cookie changed

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/Components/Pages/Login/index.js
client/src/Components/Pages/NoMatch/index.js
client/src/Components/Pages/PrivateRoute/index.js

- Made pretty instagram login button
- Created a private route. It checks whether the user has a cookie for userid, if so, loads profile page, if not, redirects to login. Need to double check that it's secure... not sure it is doing the rigth DB call

Login button

---

client/src/App.js
client/src/Components/Pages/DoneChallenges/index.js
client/src/Components/Pages/OngoingChallenges/index.js
client/src/Components/Pages/Profile/index.js
routes/API.js

- Added user challenges to state of profile component
- Moved cookies to profile component
- Conditional rendering waits until user data has been found in cookie to render profile page. That way asynchronous issues with passing props that dont exist are not a problem.

Only display user challenges

---

client/src/Components/Pages/BrowseChallenges/index.js
client/src/Components/Pages/ChallengeDetails/index.js
client/src/Components/Pages/CreateChallenges/index.js
client/src/Components/Pages/Profile/index.js

- Join challenge working
- Join challenge from project
- Button to join challenge displays only if user is not in it
- Reload components after changes in state

Update state after api calls

---

client/src/Components/Pages/DoneChallenges/index.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/ProfileNav/index.js
client/src/utils/API.js
models/Post.js
routes/API.js

-Post model updated
-Query to create a post
-Query to get all the posts that are related to the challenges that a user has joined
-Log out deletes the cookie

Model updated, queries created

---

client/package-lock.json
client/src/Components/Pages/Timeline/index.js
client/src/Components/Pages/TimelinePost/index.js
package-lock.json
routes/API.js

-Flipped the timeline...now the most recent post appears at the top
-Passed the user profile pic, so the small picture on the post belongs to the user who posted

Posts now appear from newest to oldest

---

client/src/App.js
client/src/Components/Pages/BrowseChallenges/index.js
client/src/Components/Pages/ChallengeCard/index.js
client/src/Components/Pages/ChallengeDetails/index.js
client/src/Components/Pages/CreateChallenges/index.js
client/src/Components/Pages/Login/index.js
client/src/Components/Pages/NoMatch/index.js
client/src/Components/Pages/OngoingChallenges/index.js
client/src/Components/Pages/Timeline/index.js
client/src/Components/Pages/TimelinePost/index.js
routes/API.js

-Cleaned the console.log a little
--Still some errors regarding arrow functions and nesting elements for styling

Avoid repeated challenges & posts

---

client/src/Components/AppComponents/Profile/ChallengeDetails/index.js
client/src/Components/AppComponents/Profile/ProfileNav/index.js
client/src/Components/AppComponents/Profile/Timeline/index.js
client/src/Components/AppComponents/Profile/TimelinePost/index.js

- Added link to challenge in post so you can jump to the challenge where the post was added
- When you add a post, it redirects you to your timeline, so you can see the post you added

Small improvements

---

client/src/Components/AppComponents/Profile/BrowseChallenges/index.js
client/src/Components/AppComponents/Profile/ChallengeCard/index.js
client/src/Components/AppComponents/Profile/CreateChallenges/index.js
client/src/Components/AppComponents/Profile/DoneChallenges/index.js
client/src/Components/AppComponents/Profile/OngoingChallenges/index.js
client/src/Components/BootstrapComponents/Form/index.js

-Changed Ongoing,Done and browse challenges to return a div if there is nothing to return.

Removed warnings & errors

---

client/src/Components/AppComponents/Profile/ChallengeCard/index.js

- Added moment to challenge card
- Displays end date dynamically
- Progress bar changed to bootstrap component. Dynamically changes as well
- Made end date dynamic for completed challenges
- Need to figure out how we are doing start date in browse challenge components

Dynamic challenge card for ongoing challenges

---

client/src/Components/AppComponents/Profile/BrowseChallenges/index.js
models/Challenge.js
models/Post.js

-Challenge cards in browse will show up on even if their start date is today.

Condition to display challenges

---

client/src/Components/AppComponents/Auth/Login/index.js

-Added Google Login social button (As instagram)

Removed unused login

---

client/src/Components/AppComponents/Auth/Login/index.js
client/src/Components/AppComponents/Profile/BrowseChallenges/BrowseChallenges.css
client/src/Components/AppComponents/Profile/BrowseChallenges/index.js
client/src/Components/AppComponents/Profile/ChallengeCard/ChallengeCard.css
client/src/Components/AppComponents/Profile/ChallengeCard/index.js
client/src/Components/AppComponents/Profile/ChallengesNav/index.js
client/src/Components/AppComponents/Profile/ChallengesNav/style.css
client/src/Components/AppComponents/Profile/CreateChallenges/index.js
client/src/Components/AppComponents/Profile/DoneChallenges/DoneChallenges.css
client/src/Components/AppComponents/Profile/OngoingChallenges/index.js
client/src/Components/AppComponents/Profile/OngoingChallenges/style.css
client/src/Components/AppComponents/Profile/ProfileNav/index.js
client/src/Components/AppComponents/Profile/ProfileNav/style.css
client/src/Components/AppComponents/Profile/Timeline/index.js
client/src/Components/BootstrapComponents/Form/index.js
client/src/Components/BootstrapComponents/Form/style.css
client/src/Components/BootstrapComponents/Nav/index.js
client/src/Components/BootstrapComponents/Nav/style.css

- Made some major changes on positioning things so they look a bit more clear on profile. 
- changed a lot of the route paths we were using and opted for classes. Still need to clean things up so it is more clear what is targeting what in CSS
- May have broken some things but will fix anything that happened to

Styling updates

---

client/src/Components/AppComponents/Profile/BrowseChallenges/BrowseChallenges.css
client/src/Components/AppComponents/Profile/BrowseChallenges/index.js
client/src/Components/AppComponents/Profile/ChallengeCard/ChallengeCard.css
client/src/Components/AppComponents/Profile/ChallengeCard/index.js
client/src/Components/AppComponents/Profile/ChallengeDetails/ChallengeDetails.css
client/src/Components/AppComponents/Profile/ChallengeDetails/index.js
client/src/Components/AppComponents/Profile/ChallengesNav/index.js
client/src/Components/AppComponents/Profile/CreateChallenges/index.js
client/src/Components/AppComponents/Profile/DoneChallenges/index.js
client/src/Components/AppComponents/Profile/OngoingChallenges/style.css
client/src/Components/AppComponents/Profile/Timeline/Timeline.css
client/src/Components/AppComponents/Profile/Timeline/index.js
client/src/Components/AppComponents/Profile/TimelinePost/TimelinePost.css
client/src/Components/AppComponents/Profile/TimelinePost/index.js

- Styling on various cards, fixed up timeline feed to look better
- Changed language to be "Workout" rather than "Challenge" where I could. I think this makes more sense, since it is only for athletics!

Conditional fixes

---

client/src/Components/AppComponents/Auth/Login/index.js
client/src/Components/AppComponents/Profile/ChallengeCard/index.js
client/src/Components/AppComponents/Profile/CreateChallenges/index.js
client/src/Components/AppComponents/Profile/CreateChallenges/style.css

- Quick pass at styling create workout. 
- Still need to make mobile responsive, but its a bit nicer

Create workout styling

---

client/src/Components/AppComponents/Profile/ChallengeDetails/index.js
client/src/Components/AppComponents/Profile/TimelinePost/TimelinePost.css

- Added start and end time blurbs to the details of the challenge with number of days remaining or number of days until the challenge begins

Start end times

---

client/src/Components/AppComponents/Profile/ChallengeDetails/ChallengeDetails.css
client/src/Components/AppComponents/Profile/ChallengeDetails/index.js
client/src/Components/AppComponents/Profile/CreateChallenges/index.js
client/src/Components/AppComponents/Profile/CreateChallenges/style.css

- Validation for both adding challenge and adding posts

Input validation

---

client/src/Components/AppComponents/Profile/ChallengeDetails/ChallengeDetails.css
client/src/Components/AppComponents/Profile/ChallengeDetails/index.js
client/src/Components/AppComponents/Profile/ChallengesNav/ChallengesNav.css
client/src/Components/AppComponents/Profile/ProfileNav/ProfileNav.css

- Fixed styling of mobile navbar
- color fixes
- Centering and button sizes in challenge details on mobile

Navbar mobile
